### ISSUE TITLE
USA cannot be selected as default country code

### ISSUE THREAD

**Issue by nirmalwheelhouse** [vishaldhanotiya/rn-country-picker#26]
Hi,
 Us and Canada have same country code (+1) . When I am giving default country code as 1 , Canada flag is coming instead of US flag.
There is no other extra prop to change this. Can you please resolve it

**Comment by rodel-daroy** [comment]
I have same issue

**Comment by vishaldhanotiyadev** [comment]
@rodel-daroy @nirmalwheelhouse  We added a new prop `countryId` to solve the same country code problem of different countries.
For USA its 231
For Canada its 31
