### ISSUE TITLE
How to change search bar text color

### ISSUE THREAD

**Issue by sadhnaPal** [vishaldhanotiya/rn-country-picker#50]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vishaldhanotiyadev** [comment]
@sadhnaPal I added two new properties.

 Help to change the placeholder color
 `searchBarPlaceholderTextColor`
 
 Change search Input style
 `searchInputStyle`
